In [ ]:
Jupyter notebook is used as:
    1. IDE  : can develop editor application
    2. interpreter  : in annaconda promt(cmd) can use it as interpreter...line by line execution

In [ ]:
Declare the following variables:
Int, Float, Boolean, String & print its value.
 Program to calculate the Area Of Triangle:
 Program to swap two variables:
 Program is to check if a number is positive, negative 
or 0 (Using If…elif…else).
 Program is to check if a number is Even or Odd:
 Program to print Odd number within a given range:
 Python program to find the factorial of a number:
 Program to reverse a given number:
 Program to find out the sum of Natural numbers:

In [4]:
value = 23
print(int(value))
print(float(value))
print(str(value))
print(bool(value))
print(value,"is type of",type(value))

23
23.0
23
True
23 is type of <class 'int'>


In [5]:
b =23.0
print(b,"is type of",type(b))

23.0 is type of <class 'float'>


In [8]:
#  s= (a + b + c) / 2
a = eval(input("1st side is:"))
b =eval(input("2nd side is:"))
c = eval(input("3rd side is:"))
s = (a+b+c)/2
print("Area of triangle is:",s)

1st side is:23
2nd side is:34
3rd side is:53
Area of triangle is: 55.0


In [9]:
a =100
b =200
temp = a
a=b
b =temp
print("Now value of a is:",a,"and value of b is:",b)

Now value of a is: 200 and value of b is: 100


In [10]:
a =100
b =200
a= a+b
b= a-b
a = a-b
print(a,b)

200 100


In [11]:
# Program is to check if a number is positive, or 0 (Using If…elif…else).
num = eval(input("Enter a number:"))

if num==0:
    print("Number is Zero")
elif num<0:
    print("Number is negative")
else:
    print("Number is Positive")

Enter a number:32
Number is Positive


In [12]:
num = eval(input("Enter a number:"))

if num>=0:
    if num==0:
        print("Zero")
    else:
        print("Positive")
else:
    print("Negative")

Enter a number:2
Positive


In [13]:
# Program is to check if a number is Even or Odd:
num1 = eval(input("Enter a number:"))

if num1%2==0:
    print("number is even")
else:
    print("number is odd")

Enter a number:34
number is even


In [15]:
# Program to print Odd number within a given range:
num1 = eval(input("Enter a range:"))

for i in range(1,num1):
    if i%2!=0:
        print(i)

Enter a range:9
1
3
5
7


In [46]:
#  Python program to find the factorial of a number:

# 4*3*2*1 =24
# 4*3 =12
# 12*2 = 24
# 24*1 = 24
fect_num= eval(input("Enter a num:"))
result = fect_num
for i in range(fect_num-1,1,-1):
    print(f"{result}x{i}={result*i}")
    result = result*i

Enter a num:6
6x5=30
30x4=120
120x3=360
360x2=720


In [48]:
def recur_factorial (n):
 """Function to return the factorial
 of a number using recursion"""
 if n == 1:
     return n
 else:
     return n*recur_factorial (n-1)
recur_factorial(6)

720

In [56]:
# Program to reverse a given number:
num = "12324"
print(num[-1::-1])

42321


In [71]:
num2 = eval(input("Enter a num:"))

rev = 0
while(num2>0):
    dig = num2%10
    rev = rev*10+dig
    num2 = num2//10
print(rev)

Enter a num:1234
4321


In [78]:
#  Program to find out the sum of Natural numbers:
num_n = eval(input("Enter a num:"))
result =0
for i in range(1,num_n+1):
    result = result+i
print(result)

Enter a num:14
105


In [73]:
num_n = eval(input("Enter a num:"))
result =0
while(num_n>0):
    result +=num_n
    num_n-=1
    
print(result)

Enter a num:14
105


In [79]:
# for i in range(1,14):
#     print(i)

In [ ]:
Strings:
Program to reverse a string without using 
recursion:
Program to check if string is palindrome or not:
Python Program to Replace all Occurrences of ‘a’ 
with $ in a String:
Python Program to Count the Number of Vowels 
in a String
Input Two Strings and Display the Larger String 
without Using Built-in Functions:
Count the number of digits & letter in a string:
Count Number of Lowercase Characters in a 
String:
Program to check if a Substring is Present in a 
Given String

In [92]:
# Program to reverse a string without using 
# recursion:

name = "monika"
# reverse(name)
# print(name[::-1])

 

In [89]:
# Program to check if string is palindrome or not:
#madam

string = eval(input("Enter a string:"))
if string[::]==string[::-1]:
    print("string is palindrome")
else:
    print("string is not palindrome")

Enter a string:"monika"
string is not palindrome


In [93]:
# Python Program to Replace all Occurrences of ‘a’ 
# with $ in a String:

name = "monika"
name.replace("a","$")

'monik$'

In [95]:
# Python Program to Count the Number of Vowels 
# in a String
name = "monikaaa"
vowels = ["a","e","i","o","u"]
count =0
for i in name:
    if i in vowels:
        count+=1
print(count)

5


In [3]:
#  Count the number of digits & letter in a string:
name = "monika18"
num_count = 0
char_count = 0
for s in name:
    if s.isdigit():
        num_count+=1
    else:
        char_count+=1
print("Total digits in the given string is/are:", num_count)
print("Total char in the given string is/are:", char_count)

Total digits in the given string is/are: 2
Total char in the given string is/are: 6


In [6]:
# Count Number of Lowercase Characters in a String:
string = "My Name Is Monika"
count_l =0
for i in string:
    if i.islower():
        count_l +=1
print("Total lower char in the given string is/are:",count_l)

Total lower char in the given string is/are: 10


In [9]:
# Program to check if a Substring is Present in a Given String

string = "Monika Dogra is my name"
sub_string = "name"
if sub_string in string:
    print("Yes")
else:
    print("No")

Yes


In [1]:
# dir(str)

In [ ]:
Program to Find the Largest Number in a List:
Program to Put Even and Odd elements in a List 
into Two Different Lists:
Program to Read a List of Words and Return the 
Length of the Longest One:
Create a List of Tuples with the First Element as 
the Number and Second Element as the Square 
of the Number:
Program to Remove the Duplicate Items from a 
List

In [8]:
# Program to Find the Largest Number in a List
from functools import reduce
list_num = [23,45,1,2,4,567,234]

result = reduce(lambda x,y: x if x>y else y, list_num)
result

567

In [37]:
list_num = [23,45,1,2,4,567,234]
check_list = list_num[0]

for num in range(0,len(list_num)):
    if list_num[num] >check_list:
        check_list = list_num[num]      
    else:
        pass
print(check_list) 

567


In [39]:
# dir(list)

list_num = [23,45,1,2,4,567,234]

for i in range(0,len(list_num)):
    for j in range(1,len(list_num)):
        if list_num[i]> list_num[j]:
            list_num[j] = list_num[i]
print(list_num[j])

567


In [41]:
# Program to Put Even and Odd elements in a List 
# into Two Different Lists

list_num = [23,45,1,2,4,567,234]
odd_lst = []
even_lst = []
for num in list_num:
    if num%2==0:
        even_lst.append(num)
    else:
        odd_lst.append(num)        
print("even:",even_lst)
print("odd:",odd_lst)

even: [2, 4, 234]
odd: [23, 45, 1, 567]


In [46]:
list_num = [23,45,1,2,4,567,234]
odd_lst = []
even_lst = []
result =list(filter(lambda x: even_lst.append(x) if x%2==0 else odd_lst.append(x),list_num))
print(odd_lst)
print(even_lst)

[23, 45, 1, 567]
[2, 4, 234]


In [51]:
# Program to Read a List of Words and Return the 
# Length of the Longest One:
input_list = eval(input("Enter a list of words:"))
print(type(input_list))

Enter a list of words:["Hello this is BTechGeeks  online platform"]
<class 'list'>


In [58]:
word_list = ["Hello","this","is","BTechGeeks","online","platform"]
print(len(word_list[0]))

result1 = reduce(lambda x,y: x if len(x)>len(y) else y, word_list)
print(result1)

5
BTechGeeks


In [59]:
# Create a List of Tuples with the First Element as 
# the Number and Second Element as the Square 
# of the Number:

list_num = [23,45,1,2,4,567,234]

show_result = [(x,x*x) for x in list_num]
print(show_result)

[(23, 529), (45, 2025), (1, 1), (2, 4), (4, 16), (567, 321489), (234, 54756)]


In [60]:
list_num = [23,45,1,2,4,567,234]

show1 = list(map(lambda x:(x,x*x),list_num))
print(show1)

[(23, 529), (45, 2025), (1, 1), (2, 4), (4, 16), (567, 321489), (234, 54756)]


In [61]:
# Program to Remove the Duplicate Items from a 
# List

list_num = [23,45,1,2,4,4,2,23,45,67,234]
set_items = set(list_num)
print(set_items)

{1, 2, 67, 4, 234, 45, 23}


In [64]:
list_num = [23,45,1,2,4,4,2,23,45,67,234]
filtered_list = []
for num in range(0,len(list_num)):     
    if list_num[num] not in filtered_list:
        filtered_list.append(list_num[num])
print(filtered_list)

[23, 45, 1, 2, 4, 67, 234]


In [66]:
# dir(list)

In [ ]:
list.count()

In [ ]:
Program to Check if a Given Key Exists in a 
Dictionary or Not:
Program to Sum All the Items in a Dictionary:
Program to Remove the Given Key from a 
Dictionary:
Write a Python program to iterate over dictionaries 
using for loops:
Write a Python program to sort a dictionary by 
key

In [1]:
# Program to Check if a Given Key Exists in a 
# Dictionary or Not:

dict_ = {'name':'Monika',
        'class':7,
        'rollno':101}
print(dict_.keys())

dict_keys(['name', 'class', 'rollno'])


In [2]:
print(dict_)

{'name': 'Monika', 'class': 7, 'rollno': 101}


In [9]:
key_ = 'name'
if key_ in dict_.keys():
    print("yes")
else:
    print("no")
    
#OR 
    # for k in dict_.keys():
#     if k in key_:
#         print("yes")
#     else:
#         print("no")

yes


In [14]:
# Program to Sum All the Items in a Dictionary:
dict_1 = {'name':123,
        'class':7,
        'rollno':101}
print(sum(dict_1.values()))

231


In [12]:
# dir(dict)
d= {'A':100,'B':540,'C':239}
print ("Total sum of values in the dictionary :")
print (sum (d.values ()))


Total sum of values in the dictionary :
879


In [15]:
# Write a Python program to iterate over dictionaries 
# using for loops:
d= {'A':100,'B':540,'C':239}
for k, v in d.items():
    print(f"key:{k}, value:{v}")

key:A, value:100
key:B, value:540
key:C, value:239


In [26]:
# Write a Python program to sort a dictionary by 
# key
# dir(dict)
d= {'A':100,'C':540,'B':239}
print(sorted(d.values()))
print(sorted(d))

[100, 239, 540]
['A', 'B', 'C']


In [ ]:
 Write a Python program to print the NumPy 
version in your system.
 Write a Python program to reverse an array 
(first element becomes last).
 Write a Python program to convert a list and 
tuple into arrays.
 Write a Python program to find common values 
between two arrays.
 Write a Python program compare two arrays 
using numpy.
 Write a Python program to change the 
dimension of an array.
 Write a Python program (using numpy) to sum 
of all the multiples of 3 or 5 below 100

In [27]:
# Write a Python program to print the NumPy 
# version in your system
import numpy as np
print(np.__version__)

1.21.5


In [30]:
# Write a Python program to reverse an array 
# (first element becomes last)

arr = np.arange(0,10)
print(arr)
print(arr[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [37]:
# Write a Python program to convert a list and 
# tuple into arrays

lst = [1, 2, 3, 4, 5, 6, 7, 8]
print(np.asarray(lst))

[1 2 3 4 5 6 7 8]


In [38]:
# Write a Python program to find common values 
# between two arrays.
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print(np.intersect1d(array1,array2))

[10 40]


In [44]:
# Write a Python program compare two arrays 
# using numpy
a = np.array([1, 2])
b = np.array([4, 5])

print(a>b)
print(a>=b)
print(a<=b)
print(a<b)

[False False]
[False False]
[ True  True]
[ True  True]


In [62]:
# Write a Python program to change the 
# dimension of an array.
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)
x.shape =(3,2)
print(x)
print(x.shape)
# OR
print()
print(np.reshape(x,(3,2)))
y = np.reshape(x,(3,2))
print(y)
print(y.shape)

6 rows and 0 columns
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [48]:
x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
np.reshape(x,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
# Write a Python program (using numpy) to sum 
# of all the multiples of 3 or 5 below 100
lst =  np.arange(1,10)
# for i in lst:
#     print(i)
def check(num):
    if num%3==0 or num%5==0:
        return num
    
check = list(filter(check,lst))
print(check)

[3, 5, 6, 9]


In [82]:
check = list(filter(lambda x: x if x%3==0 or x%5==0 else None,lst))
print(check)

[3, 5, 6, 9]
